### ISSUE TITLE
Videos fail to play 

### ISSUE THREAD

**Issue by danielDevelops** [bingnz/Pluralsight.bundle#2]
I have the latest version of Plex and I cannot get the videos to play on any device.  I have tried it on my Roku and my iOS device and can login and see videos but they fail to play.

**Comment by bingnz** [comment]
Hi,

See also #1 - really sorry; I didn't have notifications from GitHub turned on, hopefully you're still interested in this plugin!
If you're still having problems, try upgrading your Plex server to the latest version. If that doesn't help, please attach the log file (you can find the plugin logs for your platform using these [instructions](https://support.plex.tv/hc/en-us/articles/201106148-Channel-Log-Files)) and I can try to figure out what's going wrong.

Thanks,
David

**Comment by bingnz** [comment]
Hi, do you manage to get the plugin working?
