### ISSUE TITLE
 not showing up in plex channels  after install

### ISSUE THREAD

**Issue by makhalaf** [bingnz/Pluralsight.bundle#3]
I did everything in the install instructions but it is not showing up in plex channels

**Comment by bingnz** [comment]
Hi,

Sorry to hear that. Have you tried restarting the Plex server? Are you using Windows or Mac?

David

**Comment by makhalaf** [comment]
Hi,

Yes I tried to restart plex many times 
I use Ubuntu mate runing on Pi 3

**Comment by bingnz** [comment]
If you type `ls $PLEX_HOME/Library/Application\ Support/Plex\ Media\ Server/Plug-ins/` in the terminal, do you see Pluralsight.bundle listed? Have you installed other plugins successfully?

**Comment by bingnz** [comment]
I believe they should be installed in `/home/pi/Library/Application Support/Plex Media Server/Plug-ins`.

**Comment by makhalaf** [comment]
I tried to manually install other plugin just for test and it also not shown

**Comment by makhalaf** [comment]
I also  Disabled capability checking in plex setting but still not showing

**Comment by bingnz** [comment]
I don't have a Pi unfortunately; you might be better off asking for help on a forum for Plex on a Raspberry Pi given that this appears to affect all plugins you're attempting to use - not just this one.
I really have no idea if this plugin will work on that kind of hardware.
Did you definitely manage to find the correct path for plugins though? Another one to try is `/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins` apparently. Pretty sure `$PLEX_HOME` should resolve to the correct prefix anyway. Any luck if you just echo out what that's set to (`echo $PLEX_HOME` in a terminal)?
Another possibility is that you've installed the plugins as a different user and the plex user can't see them. There's a guide [here](https://support.plex.tv/hc/en-us/articles/200288596-Linux-Permissions-Guide) that might point you in the right direction.

**Comment by makhalaf** [comment]
thanks a lot bingnz 
It was Permissions  issue as you mentioned  I have installed the plugins as a different user and the plex user can't see them when I changed the ownership of plugin folder to plex user it worked

**Comment by bingnz** [comment]
Great news! Glad it works. I'll close this issue.
David
